name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install libutf8
      run: |
        git clone https://github.com/wmacevoy/utf8.git /tmp/utf8
        cd /tmp/utf8 && git submodule update --init
        make -C /tmp/utf8 all
        sudo make -C /tmp/utf8 install
        sudo ldconfig

    - name: make all
      run: make all

    - name: make check
      run: make check
